from html import escape
import json
PAGES={
'vehicle-transport':('Vehicle Transport South Africa','Move cars, bakkies, SUVs and non-running vehicles with suitable verified transporters.','Transport a Vehicle',['Cars and SUVs','Bakkies and 4x4s','Non-running vehicles','Dealer and auction vehicles']),
'car-transport':('Car Transport South Africa','Post a car transport request and compare quotes from verified vehicle transporters.','Move My Car',['Running cars','Non-running cars','Auction purchases','Dealer transfers']),
'bakkie-transport':('Bakkie Transport South Africa','Find suitable transport for bakkies, pickups and 4x4 vehicles across South Africa.','Move My Bakkie',['Single bakkies','Fleet transfers','Non-running bakkies','Long-distance moves']),
'non-running-vehicle-transport':('Non-Running Vehicle Transport','Move accident-damaged, incomplete or non-running vehicles with suitable loading and recovery capability.','Move a Non-Running Vehicle',['Winch loading','Recovery transport','Accident-damaged vehicles','Workshop transfers']),
'tractor-transport':('Tractor Transport South Africa','Move tractors between farms, dealers, auctions and workshops using suitable heavy-equipment transport.','Move My Tractor',['Farm tractors','Non-running tractors','Dealer deliveries','Auction collections']),
'farm-implement-transport':('Farm Implement Transport South Africa','Move planters, balers, ploughs and large agricultural implements with suitable transporters.','Move a Farm Implement',['Planters','Balers','Ploughs','Large implements']),
'agricultural-machinery-transport':('Agricultural Machinery Transport','Arrange transport for harvesters, sprayers and large agricultural machinery.','Move Agricultural Machinery',['Harvesters','Self-propelled sprayers','Large agricultural machines','Dealer and farm transfers']),
'heavy-equipment-transport':('Heavy Equipment Transport South Africa','Find suitable transport for heavy farm, construction and industrial equipment.','Move Heavy Equipment',['Farm equipment','Construction equipment','Industrial machinery','Workshop transfers']),
'lowbed-transport':('Lowbed Transport South Africa','Request lowbed transport for tractors, machinery, vehicles and large equipment.','Request Lowbed Transport',['Tractors','Machinery','Large implements','Heavy equipment']),
'towing-and-recovery':('Vehicle Towing and Recovery','Find suitable towing or recovery transport for non-running and damaged vehicles.','Request Towing or Recovery',['Non-running vehicles','Accident recovery','Workshop transport','Long-distance recovery'])}
TEMPLATE="""<!doctype html><html lang='en'><head><meta charset='utf-8'><meta name='viewport' content='width=device-width,initial-scale=1'><title>__TITLE__ | HaulMatch 360</title><meta name='description' content='__DESCRIPTION__'><meta name='robots' content='index,follow'><link rel='canonical' href='/__SLUG__'><meta property='og:title' content='__TITLE__ | HaulMatch 360'><meta property='og:description' content='__DESCRIPTION__'><meta property='og:type' content='website'><script type='application/ld+json'>__JSONLD__</script><style>body{margin:0;font-family:Segoe UI,Arial;background:#071525;color:#fff}header,main,footer{max-width:1100px;margin:auto;padding:24px}header{display:flex;justify-content:space-between;align-items:center}a{color:#b8f43f}.hero{padding:70px 24px}h1{font-size:clamp(38px,7vw,68px);line-height:1;margin:0 0 20px}p{color:#b7c7d4;line-height:1.7;font-size:18px}.btn{display:inline-block;background:#b8f43f;color:#142000;padding:15px 22px;border-radius:12px;text-decoration:none;font-weight:900}.grid{display:grid;grid-template-columns:1fr 1fr;gap:18px}section{background:#102a42;border-radius:22px;padding:28px}li{margin:12px 0;color:#dce8f2}.note{font-size:14px;color:#97aabc}@media(max-width:700px){.grid{grid-template-columns:1fr}}</style></head><body><header><strong>HaulMatch 360</strong><nav><a href='/'>Home</a></nav></header><main><div class='hero'><h1>__TITLE__</h1><p>__DESCRIPTION__</p><a class='btn' href='/?action=post-load&amp;category=__SLUG__'>__CTA__</a></div><div class='grid'><section><h2>What can be moved?</h2><ul>__CARDS__</ul></section><section><h2>How HaulMatch works</h2><ol><li>Enter the vehicle or implement details.</li><li>Select collection and delivery locations.</li><li>Receive quotes from suitable verified transporters.</li><li>Choose a transporter and track the job through proof of delivery.</li></ol></section></div><section style='margin-top:18px'><h2>Built for the right transport match</h2><p>HaulMatch 360 uses route distance, equipment requirements, transporter verification and fleet capability to support a suitable match. Exact operational addresses remain protected until the job is awarded.</p><p class='note'>Transport charges are agreed and paid directly between the customer and transporter. HaulMatch 360 provides marketplace access and workflow tools.</p></section></main><footer><a href='/legal/terms'>Terms</a> · <a href='/legal/privacy'>Privacy</a> · <a href='/legal/credits'>Credits</a></footer></body></html>"""
def page(slug):
 if slug not in PAGES:return None
 title,description,cta,items=PAGES[slug]
 structured={'@context':'https://schema.org','@type':'Service','name':title,'description':description,'areaServed':'South Africa','provider':{'@type':'Organization','name':'HaulMatch 360'}}
 return TEMPLATE.replace('__TITLE__',escape(title)).replace('__DESCRIPTION__',escape(description,quote=True)).replace('__SLUG__',escape(slug,quote=True)).replace('__CTA__',escape(cta)).replace('__CARDS__',''.join('<li>'+escape(x)+'</li>' for x in items)).replace('__JSONLD__',json.dumps(structured).replace('</','<\\/'))
def slugs():return list(PAGES.keys())
