const SHEET_ID=PropertiesService.getScriptProperties().getProperty('HAULMATCH_SHEET_ID');
const ADMIN_EMAIL=PropertiesService.getScriptProperties().getProperty('HAULMATCH_ADMIN_EMAIL');
const ADMIN_KEY=PropertiesService.getScriptProperties().getProperty('HAULMATCH_ADMIN_KEY');
function out_(o,cb){const t=JSON.stringify(o);return ContentService.createTextOutput(cb?cb+'('+t+')':t).setMimeType(cb?ContentService.MimeType.JAVASCRIPT:ContentService.MimeType.JSON)}
function doGet(e){try{const a=(e.parameter.action||'health'),cb=e.parameter.callback||'';if(a==='health')return out_({ok:true,service:'HaulMatch Marketplace Operations V1'},cb);if(a==='marketplace')return out_({ok:true,items:marketplace_()},cb);if(a==='status')return out_(status_(e.parameter.reference,e.parameter.email),cb);if(a==='admin')return out_(admin_(e.parameter.key),cb);return out_({ok:false,error:'Unknown action'},cb)}catch(x){return out_({ok:false,error:x.message},e.parameter.callback||'')}}
function doPost(e){try{const d=JSON.parse((e.parameter&&e.parameter.payload)||'{}');if(!d.formType||!d.reference)throw Error('Invalid submission');const ss=SpreadsheetApp.openById(SHEET_ID);if(d.formType==='request')saveRequest_(ss,d);else if(d.formType==='transporter')saveTransporter_(ss,d);else if(d.formType==='quote')saveQuote_(ss,d);else if(d.formType==='adminAction')adminAction_(ss,d);else throw Error('Unsupported form');return out_({ok:true,reference:d.reference})}catch(x){console.error(x);return out_({ok:false,error:x.message})}}
function sheet_(ss,n,h){let s=ss.getSheetByName(n);if(!s)s=ss.insertSheet(n);if(s.getLastRow()===0){s.appendRow(h);s.setFrozenRows(1)}return s}
const RH=['Submitted','Reference','Name','Email','Mobile','Customer Type','Transport Type','Description','Quantity','Mass','Dimensions','Collection','Delivery','Required Date','Special Handling','Category Details','Photo Link','Notes','Consent','Status','Public Note','Updated At'];
const TH=['Submitted','Reference','Contact','Company','Email','Mobile','Business Type','Services','Service Areas','Vehicles','Payload','Insurance','Registration No','Experience','Notes','Consent','Status'];
const QH=['Submitted','Quote Reference','Request Reference','Transporter Reference','Email','Mobile','Amount','Vehicle','Availability','Collection Date','Delivery Estimate','Terms','Status'];
function saveRequest_(ss,d){const s=sheet_(ss,'Transport Requests',RH);if(exists_(s,d.reference,2))return;s.appendRow([d.submittedAt,d.reference,d.fullName,d.email,d.mobile,d.customerType,d.transportType,d.itemDescription,d.quantity,d.mass,d.dimensions,d.collectionTown,d.deliveryTown,d.requiredDate,d.specialHandling,d.categoryDetails,d.photoLink,d.notes,d.consent?'YES':'NO','NEW','Request received',new Date()]);history_(ss,d.reference,'NEW','Request submitted');audit_(ss,'REQUEST_CREATED',d.reference,d.email);mail_(d.email,'HaulMatch request received '+d.reference,'Your request was received. Reference: '+d.reference+'\nStatus: NEW')}
function saveTransporter_(ss,d){const s=sheet_(ss,'Transporter Applications',TH);if(exists_(s,d.reference,2))return;s.appendRow([d.submittedAt,d.reference,d.fullName,d.company,d.email,d.mobile,d.businessType,d.services,d.serviceAreas,d.vehicles,d.payload,d.insurance,d.registrationNumber,d.experience,d.notes,d.consent?'YES':'NO','PENDING REVIEW']);audit_(ss,'TRANSPORTER_APPLIED',d.reference,d.email);mail_(d.email,'HaulMatch transporter application '+d.reference,'Application received. Reference: '+d.reference+'\nStatus: PENDING REVIEW')}
function saveQuote_(ss,d){const rs=sheet_(ss,'Transport Requests',RH),rr=find_(rs,d.requestReference,2);if(!rr)throw Error('Request not found');if(String(rs.getRange(rr,20).getValue())!=='PUBLISHED')throw Error('Request is not open for quotes');const ts=sheet_(ss,'Transporter Applications',TH),tr=find_(ts,d.transporterReference,2);if(!tr||String(ts.getRange(tr,17).getValue())!=='APPROVED')throw Error('Approved transporter reference required');const s=sheet_(ss,'Quotes',QH);if(exists_(s,d.reference,2))return;s.appendRow([d.submittedAt,d.reference,d.requestReference,d.transporterReference,d.email,d.mobile,d.amount,d.vehicle,d.availability,d.collectionDate,d.deliveryEstimate,d.terms,'SUBMITTED']);history_(ss,d.requestReference,'QUOTE RECEIVED','Transporter interest received');audit_(ss,'QUOTE_SUBMITTED',d.reference,d.requestReference);mail_(ADMIN_EMAIL,'New HaulMatch quote '+d.reference,JSON.stringify(d,null,2))}
function marketplace_(){const ss=SpreadsheetApp.openById(SHEET_ID),s=sheet_(ss,'Transport Requests',RH),v=s.getDataRange().getDisplayValues();if(v.length<2)return [];return v.slice(1).filter(r=>r[19]==='PUBLISHED').map(r=>({reference:r[1],transportType:r[6],description:r[7],quantity:r[8],mass:r[9],dimensions:r[10],collection:r[11],delivery:r[12],requiredDate:r[13],specialHandling:r[14],status:r[19],publicNote:r[20]}))}
function status_(ref,email){const ss=SpreadsheetApp.openById(SHEET_ID),s=sheet_(ss,'Transport Requests',RH),r=find_(s,String(ref||'').toUpperCase(),2);if(!r)return {ok:false,error:'Request not found'};if(String(s.getRange(r,4).getValue()).toLowerCase()!==String(email||'').toLowerCase())return {ok:false,error:'Reference and email do not match'};const qs=sheet_(ss,'Quotes',QH),qc=qs.getLastRow()<2?0:qs.getRange(2,3,qs.getLastRow()-1,1).getDisplayValues().flat().filter(x=>x===ref).length;return {ok:true,reference:ref,status:s.getRange(r,20).getDisplayValue(),transportType:s.getRange(r,7).getDisplayValue(),collection:s.getRange(r,12).getDisplayValue(),delivery:s.getRange(r,13).getDisplayValue(),publicNote:s.getRange(r,21).getDisplayValue(),quoteCount:qc}}
function admin_(key){if(!ADMIN_KEY||key!==ADMIN_KEY)return {ok:false,error:'Invalid admin key'};const ss=SpreadsheetApp.openById(SHEET_ID),r=sheet_(ss,'Transport Requests',RH),t=sheet_(ss,'Transporter Applications',TH),q=sheet_(ss,'Quotes',QH),rv=r.getDataRange().getDisplayValues(),tv=t.getDataRange().getDisplayValues();return {ok:true,counts:{newRequests:rv.slice(1).filter(x=>x[19]==='NEW').length,published:rv.slice(1).filter(x=>x[19]==='PUBLISHED').length,pendingTransporters:tv.slice(1).filter(x=>x[16]==='PENDING REVIEW').length,quotes:Math.max(0,q.getLastRow()-1)},requests:rv.slice(1).filter(x=>!['CLOSED','REJECTED'].includes(x[19])).slice(-50).reverse().map(x=>({reference:x[1],transportType:x[6],collection:x[11],delivery:x[12],status:x[19]}))}}
function adminAction_(ss,d){if(!ADMIN_KEY||d.key!==ADMIN_KEY)throw Error('Invalid admin key');const s=sheet_(ss,'Transport Requests',RH),r=find_(s,d.reference,2);if(!r)throw Error('Request not found');s.getRange(r,20).setValue(d.status);s.getRange(r,22).setValue(new Date());history_(ss,d.reference,d.status,'Admin status update');audit_(ss,'STATUS_CHANGED',d.reference,d.status);const email=s.getRange(r,4).getValue();mail_(email,'HaulMatch request update '+d.reference,'Your request status is now: '+d.status)}
function approveTransporter(reference){const ss=SpreadsheetApp.openById(SHEET_ID),s=sheet_(ss,'Transporter Applications',TH),r=find_(s,reference,2);if(!r)throw Error('Not found');s.getRange(r,17).setValue('APPROVED');audit_(ss,'TRANSPORTER_APPROVED',reference,'manual')}
function history_(ss,ref,status,note){sheet_(ss,'Status History',['Timestamp','Reference','Status','Note']).appendRow([new Date(),ref,status,note])}
function audit_(ss,event,ref,detail){sheet_(ss,'Audit Log',['Timestamp','Event','Reference','Detail']).appendRow([new Date(),event,ref,detail])}
function mail_(to,sub,body){if(to)MailApp.sendEmail(to,sub,body)}
function exists_(s,v,c){return !!find_(s,v,c)}function find_(s,v,c){if(s.getLastRow()<2)return 0;const a=s.getRange(2,c,s.getLastRow()-1,1).getDisplayValues().flat();const i=a.indexOf(v);return i<0?0:i+2}
function upgradeMarketplaceSheets(){const ss=SpreadsheetApp.openById(SHEET_ID);sheet_(ss,'Transport Requests',RH);sheet_(ss,'Transporter Applications',TH);sheet_(ss,'Quotes',QH);sheet_(ss,'Status History',['Timestamp','Reference','Status','Note']);sheet_(ss,'Risk Flags',['Timestamp','Reference','Severity','Rule','Status','Note']);sheet_(ss,'Audit Log',['Timestamp','Event','Reference','Detail']);sheet_(ss,'Settings',['Key','Value']);}
