const SHEET_ID=PropertiesService.getScriptProperties().getProperty('HAULMATCH_SHEET_ID');
const ADMIN_EMAIL=PropertiesService.getScriptProperties().getProperty('HAULMATCH_ADMIN_EMAIL');
const ADMIN_KEY=PropertiesService.getScriptProperties().getProperty('HAULMATCH_ADMIN_KEY');
const TURNSTILE_SECRET=PropertiesService.getScriptProperties().getProperty('HAULMATCH_TURNSTILE_SECRET')||'';
const DISPOSABLE=['mailinator.com','yopmail.com','guerrillamail.com','10minutemail.com','tempmail.com','temp-mail.org','sharklasers.com','throwawaymail.com'];
const RH=['Submitted','Reference','Name','Email','Mobile','Customer Type','Transport Type','Description','Quantity','Mass','Dimensions','Collection','Delivery','Required Date','Special Handling','Category Details','Photo Link','Notes','Consent','Status','Public Note','Updated At','Risk Score','Moderation Status','Device Fingerprint'];
const TH=['Submitted','Reference','Contact','Company','Email','Mobile','Business Type','Services','Service Areas','Vehicles','Payload','Insurance','Registration No','Experience','Notes','Consent','Status','Risk Score','Moderation Status','Device Fingerprint'];
const QH=['Submitted','Quote Reference','Request Reference','Transporter Reference','Email','Mobile','Amount','Vehicle','Availability','Collection Date','Delivery Estimate','Terms','Status','Risk Score'];
function out_(o,cb){const t=JSON.stringify(o);return ContentService.createTextOutput(cb?cb+'('+t+')':t).setMimeType(cb?ContentService.MimeType.JAVASCRIPT:ContentService.MimeType.JSON)}
function doGet(e){try{const a=e.parameter.action||'health',cb=e.parameter.callback||'';if(a==='health')return out_({ok:true,service:'HaulMatch Trust and Moderation'},cb);if(a==='marketplace')return out_({ok:true,items:marketplace_()},cb);if(a==='status')return out_(status_(e.parameter.reference,e.parameter.email),cb);if(a==='admin')return out_(admin_(e.parameter.key),cb);if(a==='moderation')return out_(moderation_(e.parameter.key),cb);return out_({ok:false,error:'Unknown action'},cb)}catch(x){return out_({ok:false,error:x.message},e.parameter.callback||'')}}
function doPost(e){try{const d=JSON.parse((e.parameter&&e.parameter.payload)||'{}');if(!d.formType||!d.reference||d.website)throw Error('Invalid submission');if(['request','transporter'].includes(d.formType)&&!verifyTurnstile_(d.turnstileToken))throw Error('Bot verification failed');const ss=SpreadsheetApp.openById(SHEET_ID);if(d.formType==='request')saveRequest_(ss,d);else if(d.formType==='transporter')saveTransporter_(ss,d);else if(d.formType==='quote')saveQuote_(ss,d);else if(d.formType==='adminAction')adminAction_(ss,d);else if(d.formType==='moderationAction')moderationAction_(ss,d);else if(d.formType==='transporterDecision')transporterDecision_(ss,d);else throw Error('Unsupported form');return out_({ok:true,reference:d.reference})}catch(x){console.error(x);return out_({ok:false,error:x.message})}}
function verifyTurnstile_(token){if(!TURNSTILE_SECRET)return true;if(!token)return false;const r=UrlFetchApp.fetch('https://challenges.cloudflare.com/turnstile/v0/siteverify',{method:'post',payload:{secret:TURNSTILE_SECRET,response:token},muteHttpExceptions:true});return JSON.parse(r.getContentText()).success===true}
function sheet_(ss,n,h){let s=ss.getSheetByName(n);if(!s)s=ss.insertSheet(n);if(s.getLastRow()===0){s.appendRow(h);s.setFrozenRows(1)}else ensureHeaders_(s,h);return s}
function ensureHeaders_(s,h){const old=s.getRange(1,1,1,s.getLastColumn()).getDisplayValues()[0];h.forEach(x=>{if(!old.includes(x))s.getRange(1,s.getLastColumn()+1).setValue(x)})}
function emailRisk_(email){const d=String(email||'').toLowerCase().split('@')[1]||'';return DISPOSABLE.includes(d)?50:0}
function duplicateCount_(s,value,col){if(!value||s.getLastRow()<2)return 0;return s.getRange(2,col,s.getLastRow()-1,1).getDisplayValues().flat().filter(x=>String(x).toLowerCase()===String(value).toLowerCase()).length}
function contentRisk_(text){return /crypto|bitcoin|gift card|pay before|deposit first|whatsapp only|urgent payment/i.test(String(text||''))?35:0}
function riskRequest_(s,d){let score=emailRisk_(d.email)+contentRisk_(d.itemDescription+' '+d.notes);if(duplicateCount_(s,d.mobile,5)>=2)score+=30;if(duplicateCount_(s,d.email,4)>=3)score+=20;if(duplicateCount_(s,d.deviceFingerprint,25)>=5)score+=25;return Math.min(100,score)}
function riskTransporter_(s,d){let score=emailRisk_(d.email)+contentRisk_(d.notes);if(duplicateCount_(s,d.mobile,6)>=2)score+=30;if(String(d.insurance).toLowerCase()==='no')score+=15;return Math.min(100,score)}
function saveRequest_(ss,d){const s=sheet_(ss,'Transport Requests',RH);if(find_(s,d.reference,2))return;const risk=riskRequest_(s,d),mod=risk>=50?'REVIEW REQUIRED':'PENDING REVIEW';s.appendRow([d.submittedAt,d.reference,d.fullName,d.email,d.mobile,d.customerType,d.transportType,d.itemDescription,d.quantity,d.mass,d.dimensions,d.collectionTown,d.deliveryTown,d.requiredDate,d.specialHandling,d.categoryDetails,d.photoLink,d.notes,d.consent?'YES':'NO','NEW','Request received',new Date(),risk,mod,d.deviceFingerprint]);history_(ss,d.reference,'NEW','Request submitted');audit_(ss,'REQUEST_CREATED',d.reference,'risk='+risk);if(risk>=50)flag_(ss,d.reference,risk>=75?'HIGH':'MEDIUM','AUTOMATED_REQUEST_RISK','Open','Automated trust checks');mail_(d.email,'HaulMatch request received '+d.reference,'Reference: '+d.reference+'\nStatus: NEW\nModeration: '+mod);mail_(ADMIN_EMAIL,'New HaulMatch request '+d.reference,'Risk score: '+risk+'\n'+JSON.stringify(d,null,2))}
function saveTransporter_(ss,d){const s=sheet_(ss,'Transporter Applications',TH);if(find_(s,d.reference,2))return;const risk=riskTransporter_(s,d),mod=risk>=40?'REVIEW REQUIRED':'PENDING REVIEW';s.appendRow([d.submittedAt,d.reference,d.fullName,d.company,d.email,d.mobile,d.businessType,d.services,d.serviceAreas,d.vehicles,d.payload,d.insurance,d.registrationNumber,d.experience,d.notes,d.consent?'YES':'NO','PENDING REVIEW',risk,mod,d.deviceFingerprint]);audit_(ss,'TRANSPORTER_APPLIED',d.reference,'risk='+risk);if(risk>=40)flag_(ss,d.reference,risk>=70?'HIGH':'MEDIUM','TRANSPORTER_RISK','Open','Automated trust checks');mail_(d.email,'HaulMatch transporter application '+d.reference,'Reference: '+d.reference+'\nStatus: PENDING REVIEW')}
function saveQuote_(ss,d){const rs=sheet_(ss,'Transport Requests',RH),rr=find_(rs,d.requestReference,2);if(!rr||rs.getRange(rr,20).getDisplayValue()!=='PUBLISHED')throw Error('Request is not open');const ts=sheet_(ss,'Transporter Applications',TH),tr=find_(ts,d.transporterReference,2);if(!tr||ts.getRange(tr,17).getDisplayValue()!=='APPROVED'||ts.getRange(tr,19).getDisplayValue()==='BLOCKED')throw Error('Approved transporter required');const risk=emailRisk_(d.email)+contentRisk_(d.terms);const s=sheet_(ss,'Quotes',QH);if(find_(s,d.reference,2))return;s.appendRow([d.submittedAt,d.reference,d.requestReference,d.transporterReference,d.email,d.mobile,d.amount,d.vehicle,d.availability,d.collectionDate,d.deliveryEstimate,d.terms,risk>=50?'HELD FOR REVIEW':'SUBMITTED',risk]);if(risk>=50)flag_(ss,d.reference,'HIGH','QUOTE_RISK','Open','Quote held for moderation');history_(ss,d.requestReference,'QUOTE RECEIVED','Transporter response received');audit_(ss,'QUOTE_SUBMITTED',d.reference,'risk='+risk);mail_(ADMIN_EMAIL,'New HaulMatch quote '+d.reference,JSON.stringify(d,null,2))}
function marketplace_(){const ss=SpreadsheetApp.openById(SHEET_ID),s=sheet_(ss,'Transport Requests',RH),v=s.getDataRange().getDisplayValues();return v.slice(1).filter(r=>r[19]==='PUBLISHED'&&r[23]!=='BLOCKED').map(r=>({reference:r[1],transportType:r[6],description:r[7],quantity:r[8],mass:r[9],dimensions:r[10],collection:r[11],delivery:r[12],requiredDate:r[13],specialHandling:r[14],status:r[19],publicNote:r[20]}))}
function status_(ref,email){const ss=SpreadsheetApp.openById(SHEET_ID),s=sheet_(ss,'Transport Requests',RH),r=find_(s,String(ref||'').toUpperCase(),2);if(!r)return {ok:false,error:'Request not found'};if(s.getRange(r,4).getDisplayValue().toLowerCase()!==String(email||'').toLowerCase())return {ok:false,error:'Reference and email do not match'};const qs=sheet_(ss,'Quotes',QH),qc=qs.getLastRow()<2?0:qs.getRange(2,3,qs.getLastRow()-1,1).getDisplayValues().flat().filter(x=>x===ref).length;return {ok:true,reference:ref,status:s.getRange(r,20).getDisplayValue(),transportType:s.getRange(r,7).getDisplayValue(),collection:s.getRange(r,12).getDisplayValue(),delivery:s.getRange(r,13).getDisplayValue(),publicNote:s.getRange(r,21).getDisplayValue(),quoteCount:qc}}
function admin_(key){checkAdmin_(key);const ss=SpreadsheetApp.openById(SHEET_ID),r=sheet_(ss,'Transport Requests',RH),t=sheet_(ss,'Transporter Applications',TH),q=sheet_(ss,'Quotes',QH),rv=r.getDataRange().getDisplayValues(),tv=t.getDataRange().getDisplayValues();return {ok:true,counts:{newRequests:rv.slice(1).filter(x=>x[19]==='NEW').length,published:rv.slice(1).filter(x=>x[19]==='PUBLISHED').length,pendingTransporters:tv.slice(1).filter(x=>x[16]==='PENDING REVIEW').length,quotes:Math.max(0,q.getLastRow()-1)},requests:rv.slice(1).filter(x=>!['CLOSED','REJECTED'].includes(x[19])).slice(-50).reverse().map(x=>({reference:x[1],transportType:x[6],collection:x[11],delivery:x[12],status:x[19]}))}}
function moderation_(key){checkAdmin_(key);const ss=SpreadsheetApp.openById(SHEET_ID),f=sheet_(ss,'Risk Flags',['Timestamp','Reference','Severity','Rule','Status','Note']),t=sheet_(ss,'Transporter Applications',TH),fv=f.getDataRange().getDisplayValues(),tv=t.getDataRange().getDisplayValues();return {ok:true,flags:fv.slice(1).filter(x=>x[4]==='Open').map(x=>({reference:x[1],severity:x[2],rule:x[3],note:x[5]})),transporters:tv.slice(1).filter(x=>['PENDING REVIEW','MORE INFO REQUIRED'].includes(x[16])).map(x=>({reference:x[1],company:x[3],services:x[7],risk:x[17]}))}}
function adminAction_(ss,d){checkAdmin_(d.key);const s=sheet_(ss,'Transport Requests',RH),r=find_(s,d.reference,2);if(!r)throw Error('Not found');if(d.status==='PUBLISHED'&&Number(s.getRange(r,23).getValue())>=75)throw Error('High-risk request must be cleared first');if(s.getRange(r,24).getDisplayValue()==='BLOCKED')throw Error('Blocked request cannot publish');s.getRange(r,20).setValue(d.status);s.getRange(r,22).setValue(new Date());history_(ss,d.reference,d.status,'Admin update');audit_(ss,'STATUS_CHANGED',d.reference,d.status);mail_(s.getRange(r,4).getValue(),'HaulMatch request update '+d.reference,'Status: '+d.status)}
function moderationAction_(ss,d){checkAdmin_(d.key);const f=sheet_(ss,'Risk Flags',['Timestamp','Reference','Severity','Rule','Status','Note']);for(let r=2;r<=f.getLastRow();r++)if(f.getRange(r,2).getDisplayValue()===d.reference&&f.getRange(r,5).getDisplayValue()==='Open')f.getRange(r,5).setValue(d.status);const rs=sheet_(ss,'Transport Requests',RH),rr=find_(rs,d.reference,2);if(rr)rs.getRange(rr,24).setValue(d.status);const ts=sheet_(ss,'Transporter Applications',TH),tr=find_(ts,d.reference,2);if(tr)ts.getRange(tr,19).setValue(d.status);audit_(ss,'MODERATION_'+d.status,d.reference,'admin')}
function transporterDecision_(ss,d){checkAdmin_(d.key);const s=sheet_(ss,'Transporter Applications',TH),r=find_(s,d.reference,2);if(!r)throw Error('Not found');if(d.status==='APPROVED'&&s.getRange(r,19).getDisplayValue()==='BLOCKED')throw Error('Clear block first');s.getRange(r,17).setValue(d.status);audit_(ss,'TRANSPORTER_'+d.status,d.reference,'admin');mail_(s.getRange(r,5).getValue(),'HaulMatch application update '+d.reference,'Status: '+d.status)}
function checkAdmin_(k){if(!ADMIN_KEY||k!==ADMIN_KEY)throw Error('Invalid admin key')}
function flag_(ss,ref,severity,rule,status,note){sheet_(ss,'Risk Flags',['Timestamp','Reference','Severity','Rule','Status','Note']).appendRow([new Date(),ref,severity,rule,status,note])}
function history_(ss,ref,status,note){sheet_(ss,'Status History',['Timestamp','Reference','Status','Note']).appendRow([new Date(),ref,status,note])}
function audit_(ss,event,ref,detail){sheet_(ss,'Audit Log',['Timestamp','Event','Reference','Detail']).appendRow([new Date(),event,ref,detail])}
function mail_(to,sub,body){if(to)MailApp.sendEmail(to,sub,body)}function find_(s,v,c){if(s.getLastRow()<2)return 0;const a=s.getRange(2,c,s.getLastRow()-1,1).getDisplayValues().flat();const i=a.indexOf(v);return i<0?0:i+2}
function upgradeTrustSheets(){const ss=SpreadsheetApp.openById(SHEET_ID);sheet_(ss,'Transport Requests',RH);sheet_(ss,'Transporter Applications',TH);sheet_(ss,'Quotes',QH);sheet_(ss,'Status History',['Timestamp','Reference','Status','Note']);sheet_(ss,'Risk Flags',['Timestamp','Reference','Severity','Rule','Status','Note']);sheet_(ss,'Audit Log',['Timestamp','Event','Reference','Detail']);sheet_(ss,'Blocked Identities',['Type','Value','Reason','Status']);sheet_(ss,'Settings',['Key','Value']);}
